# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', versatileimagefield.fields.VersatileImageField(upload_to='restaurant_imgs', verbose_name='RestaurantImage')),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Restaurant_favor',
            new_name='RestaurantFavor',
        ),
        migrations.RenameModel(
            old_name='Review_img',
            new_name='ReviewImg',
        ),
        migrations.RenameModel(
            old_name='Review_like',
            new_name='ReviewLike',
        ),
        migrations.RemoveField(
            model_name='restaurant_img',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='dining.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Restaurant_img',
        ),
        migrations.AddField(
            model_name='restauranttag',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dining.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantimg',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dining.Restaurant'),
        ),
    ]
