# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_auto_20161129_0604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant_favor',
            new_name='RestaurantFavor',
        ),
        migrations.RenameModel(
            old_name='Restaurant_img',
            new_name='RestaurantImg',
        ),
        migrations.RenameModel(
            old_name='Restaurant_tag',
            new_name='RestaurantTag',
        ),
        migrations.RenameModel(
            old_name='Review_img',
            new_name='ReviewImg',
        ),
        migrations.RenameModel(
            old_name='Review_like',
            new_name='ReviewLike',
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='dining.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
