# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0003_auto_20161201_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttag',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='dining.Restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dining.Restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='restauranttag',
            unique_together=set([('restaurant', 'name')]),
        ),
    ]
