# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 07:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dining', '0004_auto_20161202_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantfavor',
            unique_together=set([('user', 'restaurant')]),
        ),
    ]
