# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dining', '0005_auto_20161202_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimg',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dining.Review'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantfavor',
            unique_together=set([('user', 'restaurant')]),
        ),
    ]
