# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0006_auto_20161203_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantfavor',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favors', to='dining.Restaurant'),
        ),
    ]
