# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0007_auto_20161206_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dining.Review'),
        ),
    ]
