# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0008_auto_20161206_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='restaurantfavor',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='restaurantimg',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='restauranttag',
            options={'ordering': ['restaurant', 'name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='reviewimg',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='reviewlike',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_average',
            field=models.FloatField(default=0),
        ),
    ]
