# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0009_auto_20161207_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='review_average',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
