# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0010_auto_20161208_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
