# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0011_auto_20161208_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='total_like',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
